version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: "article_processor"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5252"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5444:5432"
    networks:
      - article
  backend:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - article
networks:
  article:
    external: true