"""change field names

Revision ID: 2d60d228db77
Revises: 7bc8bf8f40d9
Create Date: 2023-05-21 23:22:35.345165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d60d228db77'
down_revision = '7bc8bf8f40d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_form', sa.Column('formatted_docs_id', sa.INTEGER(), nullable=True))
    op.add_column('article_form', sa.Column('attached_docs_id', sa.INTEGER(), nullable=True))
    op.drop_constraint('article_form_formatted_docs_filename_fkey', 'article_form', type_='foreignkey')
    op.drop_constraint('article_form_attached_docs_filename_fkey', 'article_form', type_='foreignkey')
    op.create_foreign_key(None, 'article_form', 'file', ['formatted_docs_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(None, 'article_form', 'file', ['attached_docs_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('article_form', 'attached_docs_filename')
    op.drop_column('article_form', 'formatted_docs_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_form', sa.Column('formatted_docs_filename', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('article_form', sa.Column('attached_docs_filename', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article_form', type_='foreignkey')
    op.drop_constraint(None, 'article_form', type_='foreignkey')
    op.create_foreign_key('article_form_attached_docs_filename_fkey', 'article_form', 'file', ['attached_docs_filename'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('article_form_formatted_docs_filename_fkey', 'article_form', 'file', ['formatted_docs_filename'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_column('article_form', 'attached_docs_id')
    op.drop_column('article_form', 'formatted_docs_id')
    # ### end Alembic commands ###
