"""add article fields

Revision ID: 3412a95b1b9e
Revises: 2d60d228db77
Create Date: 2023-06-02 20:17:30.555135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3412a95b1b9e'
down_revision = '2d60d228db77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_form', sa.Column('list_of_references', sa.VARCHAR(), nullable=True))
    op.add_column('article_form', sa.Column('keywords_rus', sa.VARCHAR(), nullable=True))
    op.add_column('article_form', sa.Column('keywords_eng', sa.VARCHAR(), nullable=True))
    op.add_column('article_form', sa.Column('title_rus', sa.VARCHAR(), nullable=True))
    op.add_column('article_form', sa.Column('title_eng', sa.VARCHAR(), nullable=True))
    op.add_column('article_form', sa.Column('abstract_rus', sa.VARCHAR(), nullable=True))
    op.add_column('article_form', sa.Column('abstract_eng', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_form', 'abstract_eng')
    op.drop_column('article_form', 'abstract_rus')
    op.drop_column('article_form', 'title_eng')
    op.drop_column('article_form', 'title_rus')
    op.drop_column('article_form', 'keywords_eng')
    op.drop_column('article_form', 'keywords_rus')
    op.drop_column('article_form', 'list_of_references')
    # ### end Alembic commands ###
