"""inital

Revision ID: 7bc8bf8f40d9
Revises: 
Create Date: 2023-05-16 16:09:10.718798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc8bf8f40d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('size_kb', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('surname', sa.VARCHAR(), nullable=False),
    sa.Column('place_of_study', sa.VARCHAR(), nullable=False),
    sa.Column('study_group_number', sa.VARCHAR(), nullable=False),
    sa.Column('place_of_work', sa.VARCHAR(), nullable=True),
    sa.Column('social_network_url', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('password_salt', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('article_form',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('annotation', sa.VARCHAR(), nullable=True),
    sa.Column('scientific_adviser_fullname', sa.VARCHAR(), nullable=True),
    sa.Column('scientific_adviser_academic_degree', sa.VARCHAR(), nullable=True),
    sa.Column('scientific_adviser_academic_title', sa.VARCHAR(), nullable=True),
    sa.Column('scientific_adviser_institute', sa.VARCHAR(), nullable=True),
    sa.Column('scientific_adviser_department', sa.VARCHAR(), nullable=True),
    sa.Column('formatted_docs_filename', sa.INTEGER(), nullable=True),
    sa.Column('attached_docs_filename', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attached_docs_filename'], ['file.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['formatted_docs_filename'], ['file.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_session',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expired_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('refresh_token_expired_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', 'token')
    )
    op.create_table('anti_plagiarism_result',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('percentage_of_uniqueness', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article_form.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_author',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article_form.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_author')
    op.drop_table('anti_plagiarism_result')
    op.drop_table('user_session')
    op.drop_table('article_form')
    op.drop_table('user')
    op.drop_table('file')
    # ### end Alembic commands ###
