"""add udc

Revision ID: ce8c95209c5b
Revises: e021030e57fd
Create Date: 2023-06-14 00:59:52.348557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8c95209c5b'
down_revision = 'e021030e57fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_form', sa.Column('udc', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_form', 'udc')
    # ### end Alembic commands ###
