"""delete useless fields

Revision ID: e021030e57fd
Revises: 3412a95b1b9e
Create Date: 2023-06-04 19:10:19.599538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e021030e57fd'
down_revision = '3412a95b1b9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_form', 'name')
    op.drop_column('article_form', 'annotation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_form', sa.Column('annotation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('article_form', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
