from app.database.entities.anti_plagiarism_result_entity import AntiPlagiarismResultEntity
from app.database.entities.article_author_entity import ArticleAutorEntity
from app.database.entities.article_form_entity import ArticleFormEntity
from app.database.entities.file_entity import FileEntity
from app.database.entities.user_entity import UserEntity
from app.database.entities.user_session_entity import UserSessionEntity
